### ISSUE TITLE
Duda sobre ejercicio 4 del TP integrador

### ISSUE THREAD

**Issue by LucasK237** [pdep-mit/bitacora-de-clase#1]
Buenas noches profe. Le queria hacer una consulta sobre un ejercicio que no me queda claro como realizarlo, y si bien con mi grupo lo pudimos hacer creo que lo resolvimos de una forma extraña la cual no me queda del todo clara.
Es la funcion del punto 4 que esta declarada de la siguiente forma

ordenarPor :: Ord a => (b -> a) -> [b] -> [b]

Por lo que tengo entendido debo ordenar una lista de deseos de un humano (habiendo filtrado previamente los deseosTerrenales) de menor a mayor, pero no tengo bien en claro como hacerlo yo, tampoco me queda claro como hacer una funcion que me vaya ordenando de menor a mayor segun la ponderacion (en este caso la espiritualidad)

Muchas gracias.

**Comment by mmatos** [comment]
Hola Lucas, este no es el lugar para dudas de tp (es el repo con el material de clase).

Cualquier duda pueden consultar por su canal de discord o abriendo un issue en el repositorio de su tp integrador.

Saludos
